name: henutsen_cli

description: Henutsen client application for inventory management

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.10+97

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build_runner: ^1.12.2
  chainway_r6_client_functions:
    #git:
      #url: git@github.com:Henutsen/chainway_r6_plugin.git
      #path: chainway_r6_client_functions
    path: ../chainway_r6_plugin/chainway_r6_client_functions/
  charts_flutter: ^0.12.0
    #git:
      #url: https://github.com/google/charts.git
      #path: charts_flutter
  country_code_picker: ^2.0.2
  csv: ^5.0.0
  csv_parser:
    path: ../csv/csv_parser
  csv_serializable_generator:
    path: ../csv/csv_serializable_generator
  email_validator: ^2.0.1
  excel: ^2.0.0-null-safety-2
  flutter_easyloading: ^3.0.0
  file_download:
    #git: git@github.com:AudiSoft/file_download.git
    path: ../file_download/
  file_picker: ^3.0.0
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  flutter_file_dialog: ^2.0.0
  flutter_spinkit: ^5.1.0
  gs1:
    #git: git@github.com:Henutsen/gs1.git
    path: ../gs1/
  http: ^0.13.1
  intl: ^0.17.0
  json_annotation: ^4.0.1
  package_info_plus: ^1.0.0
  photo_view: ^0.13.0
  platform: ^3.1.0
  postek_plugin:
    #git: git@github.com:Henutsen/postek_plugin.git
    path: ../postek_plugin/
  provider: ^5.0.0
  rflutter_alert: ^2.0.2
  sentry_flutter: ^5.0.0
  splashscreen: ^1.3.5
  subscription:
    #git: git@github.com:AudiSoft/subscriptions.git
    path: ../subscriptions/
  universal_html: ^2.0.7

dev_dependencies:
  # Standards and best practices used internally at AudiSoft Consulting.
  dart_standards:
    path: ../dart_standards
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.0

flutter:
  uses-material-design: true

  assets:
    - images/logo_ini.png
    - images/logo_white.png
    - images/logo.png
    - images/iconoBienvenida.png
    - images/iconoInformesNoSel.png
    - images/iconoInformesSel.png
    - images/iconoCargaMasivaNoSel.png
    - images/iconoCargaMasivaSel.png

    - images/iconoRol.png

    - images/iconoConteoNoSel.png
    - images/iconoConteoSel.png
    - images/iconoGestionNoSel.png
    - images/iconoGestionSel.png
    - images/iconoModificar.png
    - images/iconoPlantilla.png
    - images/iconoCargar.png
    - images/iconoVisualizar.png
    - images/iconoImprimir.png
    - images/iconoAgregar.png
    - images/iconoAgregarFoto.png
    - images/iconoEditarFoto.png
    - images/iconoUbicacion.png
    - images/iconoUsuario.png
    - images/iconoEmpresa.png
    - images/iconoEliminar.png
    - images/iconoSinCargas.png
    - images/iconoBuscar.png
    - images/sedes.png
    - images/Default-welcomer.png
    - config/

  fonts:
    - family: BalooTamma2
      fonts:
        - asset: fonts/BalooTamma2-Regular.ttf
        - asset: fonts/BalooTamma2-Medium.ttf
          weight: 200
        - asset: fonts/BalooTamma2-SemiBold.ttf
          weight: 400
        - asset: fonts/BalooTamma2-Bold.ttf
          weight: 600
        - asset: fonts/BalooTamma2-ExtraBold.ttf
          weight: 800
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Italic.ttf
          style: italic
        - asset: fonts/Lato-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: fonts/Lato-LightItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/Lato-BoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Lato-BlackItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/Lato-Thin.ttf
          weight: 100
        - asset: fonts/Lato-Light.ttf
          weight: 200
        - asset: fonts/Lato-Bold.ttf
          weight: 600
        - asset: fonts/Lato-Black.ttf
          weight: 800
